codecov:
  branch: develop

coverage:
  precision: 2
  round: nearest
  range: "50...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 2.0
        branches:
          - master

    patch:
      default:
        target: auto
        branches:
          - master

comment:
  layout: header, diff, changes, sunburst, uncovered
  behavior: default
  branches:
    - master
